#Exercise 2B Cleaning Up Data

In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv("test_data.csv") 
df

   ID      Name   Age       City  Score
0   1    Alexus  25.0         NY   85.0
1   2     Blake   NaN         LA   92.0
2   3   Charles  22.0    Chicago   -1.0
3   4     Smaya  19.0    Houston   65.0
4   5  Victoria  31.0    Phoenix   78.0
5   6     Sonia  35.0     Boston    NaN
6   7     Lorah   NaN     Austin   55.0
7   8     Naomi  18.0  San Diego   90.0

In [3]:
df.describe()

            ID       Age      Score
count  8.00000   6.00000   7.000000
mean   4.50000  25.00000  66.285714
std    2.44949   6.78233  32.576650
min    1.00000  18.00000  -1.000000
25%    2.75000  19.75000  60.000000
50%    4.50000  23.50000  78.000000
75%    6.25000  29.50000  87.500000
max    8.00000  35.00000  92.000000

## Filtering a DataFrame

In [5]:
df[df["Age"]>18]

   ID      Name   Age     City  Score
0   1    Alexus  25.0       NY   85.0
2   3   Charles  22.0  Chicago   -1.0
3   4     Smaya  19.0  Houston   65.0
4   5  Victoria  31.0  Phoenix   78.0
5   6     Sonia  35.0   Boston    NaN

In [7]:
df[(df["Score"]>50) & (df["Score"] <100)]

   ID      Name   Age       City  Score
0   1    Alexus  25.0         NY   85.0
1   2     Blake   NaN         LA   92.0
3   4     Smaya  19.0    Houston   65.0
4   5  Victoria  31.0    Phoenix   78.0
6   7     Lorah   NaN     Austin   55.0
7   8     Naomi  18.0  San Diego   90.0

## Modifying a DataFrame

In [8]:
df_cleaned = df.drop(df[df["Score"] < 0].index) 

df_cleaned

   ID      Name   Age       City  Score
0   1    Alexus  25.0         NY   85.0
1   2     Blake   NaN         LA   92.0
3   4     Smaya  19.0    Houston   65.0
4   5  Victoria  31.0    Phoenix   78.0
5   6     Sonia  35.0     Boston    NaN
6   7     Lorah   NaN     Austin   55.0
7   8     Naomi  18.0  San Diego   90.0

In [9]:
df_cleaned = df_cleaned.drop(columns=["City"])
df_cleaned

   ID      Name   Age  Score
0   1    Alexus  25.0   85.0
1   2     Blake   NaN   92.0
3   4     Smaya  19.0   65.0
4   5  Victoria  31.0   78.0
5   6     Sonia  35.0    NaN
6   7     Lorah   NaN   55.0
7   8     Naomi  18.0   90.0

In [10]:
df_cleaned["Age"] = df_cleaned["Age"].fillna(df_cleaned["Age"].mean())

df_cleaned

   ID      Name   Age  Score
0   1    Alexus  25.0   85.0
1   2     Blake  25.6   92.0
3   4     Smaya  19.0   65.0
4   5  Victoria  31.0   78.0
5   6     Sonia  35.0    NaN
6   7     Lorah  25.6   55.0
7   8     Naomi  18.0   90.0

In [11]:
df_cleaned["Score"] = df_cleaned["Score"].replace(0, df_cleaned["Score"].mean())

df_cleaned

   ID      Name   Age  Score
0   1    Alexus  25.0   85.0
1   2     Blake  25.6   92.0
3   4     Smaya  19.0   65.0
4   5  Victoria  31.0   78.0
5   6     Sonia  35.0    NaN
6   7     Lorah  25.6   55.0
7   8     Naomi  18.0   90.0

In [12]:
df_cleaned = df_cleaned.dropna()

df_cleaned

   ID      Name   Age  Score
0   1    Alexus  25.0   85.0
1   2     Blake  25.6   92.0
3   4     Smaya  19.0   65.0
4   5  Victoria  31.0   78.0
6   7     Lorah  25.6   55.0
7   8     Naomi  18.0   90.0

In [13]:
df_cleaned = df_cleaned.set_index("ID")

df_cleaned

        Name   Age  Score
ID
1     Alexus  25.0   85.0
2      Blake  25.6   92.0
4      Smaya  19.0   65.0
5   Victoria  31.0   78.0
7      Lorah  25.6   55.0
8      Naomi  18.0   90.0